version: "3.8"

networks:
  haseul_bot:
volumes:
  pg_data:


services:
  haseul-bot:
    image: haseul-bot:latest
    container_name: haseul-bot
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - sushii-image-server
    env_file:
      - .env
    networks:
      - haseul_bot
  postgres:
    image: postgres:15.4
    container_name: postgres
    command: postgres -c shared_buffers=512MB
    restart: unless-stopped
    shm_size: 512mb
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    networks:
      - haseul_bot
  sushii-image-server:
    image: sushii-image-server:5.2.3
    container_name: sushii-image-server
    build:
      context: .
      dockerfile: ./build/sushii-image-server/Dockerfile
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    expose:
      - "$SUSHII_IMAGE_SERVER_PORT"
    volumes:
      # Handlebar template files
      - ./web/templates:/app/templates:ro
    networks:
      - haseul_bot
